#ifndef USH_IMPL_PROTOCOL_H
#define USH_IMPL_PROTOCOL_H

#include "ush_type.h"


#define USH_IMPL_PROTOCOL_TOUCH_ID_LEN (4) // int32

#define USH_IMPL_PROTOCOL_TOUCH_ID_PING  (0x00000000)
#define USH_IMPL_PROTOCOL_TOUCH_ID_REG   (0x00010000)

#define USH_IMPL_PROTOCOL_TOUCH_ID_PING_PROI (5)
#define USH_IMPL_PROTOCOL_TOUCH_ID_PONG_PROI (5)
#define USH_IMPL_PROTOCOL_TOUCH_ID_REG_PROI (5)


#endif // USH_IMPL_PROTOCOL_H
